// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/casefile-wordmark/Editorial.tsx": () => import("../components/mockups/casefile-wordmark/Editorial.tsx"),
  "./components/mockups/casefile-wordmark/Geometric.tsx": () => import("../components/mockups/casefile-wordmark/Geometric.tsx"),
  "./components/mockups/casefile-wordmark/Mono.tsx": () => import("../components/mockups/casefile-wordmark/Mono.tsx")
};
